### ISSUE TITLE
Infinite Journal Upgrades Removed Upon Reloading

### ISSUE THREAD

**Issue by imakunee** [twanvl/sts-mad-science-mod#12]
When loading a saved game with cards that normally can't be upgraded more than once but have been due to the effect of the Infinite Journal those cards will be loaded as having been upgraded only once. Tested using:
Slay the Spire 09-06-2018
BaseMod 3.2.2
MadScienceMod 0.2.1

Thank you very much for making this mod. It has been and continues to be a lot of fun!

**Comment by twanvl** [comment]
This is fixed in the next release.
Note that the problem actually happened when loading a save file, so saves made with older versions should now load correctly.
