### ISSUE TITLE
Buffered with zero damage triggers BandageBotPower

### ISSUE THREAD

**Issue by Jazzepi** [twanvl/sts-mad-science-mod#14]
If you have buffer up, and get hit, buffer reduces the damage to 0, but onAttacked still triggers and the damage must be > 0 at that point. Maybe the buffer trigger is lower in the call order.

There is a "atDamageFinalRecieve" which contains both damage, and damage type. Perhaps the buffer will have applied by then?

**Comment by twanvl** [comment]
Buffer applies in `onLoseHP`, which is unfortunately way too late. I could make BandageBot explicitly check for the buffer power.

**Comment by Jazzepi** [comment]
How would you check for buffer? If the buffer is used up before coming to the call how would you know they had one?

**Comment by twanvl** [comment]
BufferPower.onLoseHp always happens *after* BandageBotPower.onAttacked. So there I can check if the player has BufferPower, and in that case don't trigger.

**Comment by Jazzepi** [comment]
Dumb question, how do you know the ordering?

**Comment by twanvl** [comment]
From looking at AbstractPlayer.damage. There p.onAttacked is called before p.onLoseHp.

**Comment by Jazzepi** [comment]
Oh sorry I got confused. Somehow I thought you were referencing the same callback method (onLoseHp) for both.
